import { StyleSheet } from '@react-pdf/renderer'

// Shared PDF styles aligned with the app's inline-style design language
// (DM Sans, #1A1A18 body text, #534AB7 brand, #FAFAF8 page bg).
// We rely on the default Helvetica family for PDF since DM Sans would require
// explicit font registration + font files; the Helvetica fallback keeps the
// PDF clean without adding asset dependencies for v1.

export const COLORS = {
  text: '#1A1A18',
  textMuted: '#6E6E6A',
  textFaint: '#8A8A86',
  border: '#E4E4E2',
  borderLight: '#F0F0EE',
  bg: '#FAFAF8',
  surface: '#FFFFFF',
  purple: '#534AB7',
  purpleLight: '#F6F5FF',
  purpleBorder: '#D8D5F5',
  green: '#1D9E75',
  greenLight: '#F0FAF6',
  warning: '#D68910',
  warningLight: '#FFFBF0',
}

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 48,
    paddingHorizontal: 48,
    fontSize: 10.5,
    lineHeight: 1.55,
    color: COLORS.text,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  docTitle: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.text,
    marginBottom: 4,
  },
  docSubtitle: {
    fontSize: 10,
    color: COLORS.textFaint,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    marginTop: 14,
    marginBottom: 6,
    color: COLORS.text,
  },
  h1: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginTop: 16, marginBottom: 8 },
  h2: { fontSize: 14, fontFamily: 'Helvetica-Bold', marginTop: 14, marginBottom: 6 },
  h3: { fontSize: 12, fontFamily: 'Helvetica-Bold', marginTop: 12, marginBottom: 4 },
  paragraph: { marginBottom: 6 },
  mutedLabel: {
    fontSize: 8.5,
    color: COLORS.textFaint,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  callout: {
    padding: 10,
    borderRadius: 6,
    marginVertical: 8,
    borderLeft: `3 solid ${COLORS.purple}`,
    backgroundColor: COLORS.purpleLight,
  },
  calloutTitle: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.purple,
    marginBottom: 3,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  quote: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginVertical: 10,
    borderLeft: `3 solid ${COLORS.purpleBorder}`,
    backgroundColor: COLORS.purpleLight,
    fontStyle: 'italic',
  },
  divider: {
    borderBottom: `1 solid ${COLORS.border}`,
    marginVertical: 12,
  },
  table: {
    borderTop: `1 solid ${COLORS.border}`,
    borderLeft: `1 solid ${COLORS.border}`,
    borderRight: `1 solid ${COLORS.border}`,
    borderRadius: 4,
    marginVertical: 8,
  },
  tr: { flexDirection: 'row', borderBottom: `1 solid ${COLORS.border}` },
  th: {
    flex: 1,
    paddingVertical: 6,
    paddingHorizontal: 8,
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    backgroundColor: COLORS.bg,
  },
  td: {
    flex: 1,
    paddingVertical: 6,
    paddingHorizontal: 8,
    fontSize: 10,
  },
  checklistRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 4 },
  checkbox: {
    width: 10,
    height: 10,
    border: `1 solid ${COLORS.border}`,
    borderRadius: 2,
    marginRight: 6,
    marginTop: 2,
  },
  checkboxDone: {
    width: 10,
    height: 10,
    border: `1 solid ${COLORS.green}`,
    backgroundColor: COLORS.greenLight,
    borderRadius: 2,
    marginRight: 6,
    marginTop: 2,
  },
  timelineRow: { flexDirection: 'row', marginBottom: 8 },
  timelineDate: { width: 64, fontSize: 9, color: COLORS.textMuted, marginTop: 1 },
  chartContainer: {
    borderRadius: 6,
    border: `1 solid ${COLORS.border}`,
    padding: 10,
    marginVertical: 8,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 8,
    color: COLORS.textFaint,
    textAlign: 'center',
  },
  badge: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    alignSelf: 'flex-start',
  },
})
